### ISSUE TITLE
[BUG] DataClass montage method not working with scikit-image==0.20.0

### ISSUE THREAD

**Issue by claudia-hm** [MedMNIST/MedMNIST#30]
**Bug description**

When calling the method `montage` from `DataClass` the following error appears:
 
`TypeError: montage() got an unexpected keyword argument 'multichannel'`

Last week skimage was updated to version 0.20.0 and the method `montage` from`DataClass` is no longer working. In the [tutorial notebook](https://colab.research.google.com/github/MedMNIST/MedMNIST/blob/main/examples/getting_started.ipynb), this method is used to plot images (cell number 8), and skimage already displays this warning:

`/usr/local/lib/python3.9/dist-packages/medmnist/utils.py:25: FutureWarning: multichannel is a deprecated argument name for montage. It will be removed in version 1.0. Please use channel_axis instead.
  montage_arr = skimage_montage(sel_img, multichannel=(n_channels == 3))`

So, now with the new skimage version the argument `multichannel`is deprecated.

**How to reproduce this error?**

1. Update skimage to the latest version (`pip install scikit-image==0.20.0`)
2. Run the following snippet
```
import medmnist
from medmnist import INFO
import torchvision.transforms as transforms
import skimage
print(f"Skimage v{skimage.__version__}")
print(f"MedMNIST v{medmnist.__version__} @ {medmnist.HOMEPAGE}")

data_flag = 'pathmnist'
info = INFO[data_flag]
download = True

DataClass = getattr(medmnist, info['python_class'])
data_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[.5], std=[.5])
])
# load the data
train_dataset = DataClass(split='train', transform=data_transform, download=download)
train_dataset.montage(length=1)
```

**Additional context**
A temporary workaround to bypass this error is to modify the requirements.txt file enforcing `scikit-image==0.19.0`

**Comment by duducheng** [comment]
Hi @claudia-hm,

Thanks for your bug report!

I have fixed the API compatible for scikit-image version to higher or lower than 0.20.0.

Jiancheng

**Comment by claudia-hm** [comment]
Hello,

Thank you @duducheng for taking care of this issue. 

At the moment, the bug persists and medmnist is not fully compatible with skimage 0.20.0. I see that this bug has been solved for the file medmnist/utils.py, but there is another call to skimage montage method on line 133 of medmnist/dataset.py, that causes the above code to crash. 

Kind regards,

Claudia

**Comment by duducheng** [comment]
Hi @claudia-hm,

I think I have already solved this. Have you reinstalled medmnist? 

    pip install --upgrade medmnist 

or install from git

**Comment by claudia-hm** [comment]
Thanks! Everything is working now 🙌

**Comment by duducheng** [comment]
Thanks for the bug reporting!
